
    - name: Install InfluxDB
      yum:
        name: influxdb
        state: present

    - name: Start and enable InfluxDB service
      systemd:
        name: influxdb
        state: started
        enabled: yes
