---
    - name: Install InfluxDB
      apt:
        name: influxdb
        state: present

    - name: Start and enable InfluxDB service
      service:
        name: influxdb
        state: started
        enabled: yes

    - name: Install Grafana APT repository
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present
        filename: grafana

    - name: Add Grafana APT key
      apt_key:
        url: https://packages.grafana.com/gpg.key

    - name: Install Grafana
      apt:
        name: grafana
        state: present

    - name: Start and enable Grafana service
      service:
        name: grafana-server
        state: started
        enabled: yes
