---
    - name: Install InfluxDB
      apt:
        name: influxdb
        state: present

    - name: Start and enable InfluxDB service
      service:
        name: influxdb
        state: started
        enabled: yes
